package com.invoiceme.common.services;

import com.invoiceme.common.exceptions.PdfGenerationException;
import com.invoiceme.invoice.commands.dto.InvoiceResponseDTO;
import com.invoiceme.invoice.commands.dto.LineItemResponseDTO;
import com.invoiceme.invoice.domain.InvoiceStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for ITextInvoicePdfService.
 *
 * These tests verify the PDF generation service logic including:
 * - Valid PDF byte array generation
 * - PDF content validation
 * - Error handling for null inputs
 * - Template rendering integration
 * - Performance expectations
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("ITextInvoicePdfService Unit Tests")
class ITextInvoicePdfServiceTest {

    @Mock
    private TemplateEngine templateEngine;

    private ITextInvoicePdfService pdfService;

    @BeforeEach
    void setUp() {
        pdfService = new ITextInvoicePdfService(templateEngine);
    }

    @Test
    @DisplayName("generateInvoicePdf should return valid PDF bytes for valid invoice")
    void generateInvoicePdf_WithValidInvoice_ReturnsValidPdfBytes() {
        // Given: Sample invoice DTO
        InvoiceResponseDTO invoice = createSampleInvoice();

        // Mock template engine to return valid HTML
        when(templateEngine.process(anyString(), any(Context.class)))
            .thenReturn(createSimpleHtml(invoice));

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is valid and contains data
        assertNotNull(pdfBytes, "PDF bytes should not be null");
        assertTrue(pdfBytes.length > 0, "PDF should contain data");
        assertTrue(isPdfValid(pdfBytes), "Generated bytes should be a valid PDF");

        // Verify template was called
        verify(templateEngine, times(1)).process(anyString(), any(Context.class));
    }

    @Test
    @DisplayName("generateInvoicePdf should throw IllegalArgumentException when invoice is null")
    void generateInvoicePdf_WithNullInvoice_ThrowsIllegalArgumentException() {
        // When/Then: Attempt to generate PDF with null invoice
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> pdfService.generateInvoicePdf(null)
        );

        assertEquals("Invoice cannot be null", exception.getMessage());
        verify(templateEngine, never()).process(anyString(), any(Context.class));
    }

    @Test
    @DisplayName("generateInvoicePdf should throw PdfGenerationException when template rendering fails")
    void generateInvoicePdf_WhenTemplateRenderingFails_ThrowsPdfGenerationException() {
        // Given: Invoice and template engine that throws exception
        InvoiceResponseDTO invoice = createSampleInvoice();
        when(templateEngine.process(anyString(), any(Context.class)))
            .thenThrow(new RuntimeException("Template not found"));

        // When/Then: Attempt to generate PDF
        PdfGenerationException exception = assertThrows(
            PdfGenerationException.class,
            () -> pdfService.generateInvoicePdf(invoice)
        );

        assertTrue(exception.getMessage().contains("INV-2025-0001"));
        assertNotNull(exception.getCause());
        verify(templateEngine, times(1)).process(anyString(), any(Context.class));
    }

    @Test
    @DisplayName("generateInvoicePdfStream should return valid InputStream")
    void generateInvoicePdfStream_WithValidInvoice_ReturnsValidStream() throws Exception {
        // Given: Sample invoice
        InvoiceResponseDTO invoice = createSampleInvoice();
        when(templateEngine.process(anyString(), any(Context.class)))
            .thenReturn(createSimpleHtml(invoice));

        // When: Generate PDF stream
        InputStream pdfStream = pdfService.generateInvoicePdfStream(invoice);

        // Then: Stream is valid and contains PDF data
        assertNotNull(pdfStream, "PDF stream should not be null");
        byte[] pdfBytes = pdfStream.readAllBytes();
        assertTrue(pdfBytes.length > 0, "PDF stream should contain data");
        assertTrue(isPdfValid(pdfBytes), "Stream should contain valid PDF");

        pdfStream.close();
    }

    @Test
    @DisplayName("generateInvoicePdfStream should throw IllegalArgumentException when invoice is null")
    void generateInvoicePdfStream_WithNullInvoice_ThrowsIllegalArgumentException() {
        // When/Then: Attempt to generate stream with null invoice
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> pdfService.generateInvoicePdfStream(null)
        );

        assertEquals("Invoice cannot be null", exception.getMessage());
    }

    @Test
    @DisplayName("generateInvoicePdf with OutputStream should write PDF to stream")
    void generateInvoicePdfWithOutputStream_WithValidInvoice_WritesPdfToStream() {
        // Given: Sample invoice and output stream
        InvoiceResponseDTO invoice = createSampleInvoice();
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        when(templateEngine.process(anyString(), any(Context.class)))
            .thenReturn(createSimpleHtml(invoice));

        // When: Generate PDF to stream
        pdfService.generateInvoicePdf(invoice, outputStream);

        // Then: Stream contains valid PDF
        byte[] pdfBytes = outputStream.toByteArray();
        assertTrue(pdfBytes.length > 0, "Output stream should contain data");
        assertTrue(isPdfValid(pdfBytes), "Output stream should contain valid PDF");
    }

    @Test
    @DisplayName("generateInvoicePdf with OutputStream should throw IllegalArgumentException when invoice is null")
    void generateInvoicePdfWithOutputStream_WithNullInvoice_ThrowsIllegalArgumentException() {
        // Given: Valid output stream but null invoice
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        // When/Then: Attempt to generate PDF
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> pdfService.generateInvoicePdf(null, outputStream)
        );

        assertEquals("Invoice cannot be null", exception.getMessage());
    }

    @Test
    @DisplayName("generateInvoicePdf with OutputStream should throw IllegalArgumentException when output stream is null")
    void generateInvoicePdfWithOutputStream_WithNullOutputStream_ThrowsIllegalArgumentException() {
        // Given: Valid invoice but null output stream
        InvoiceResponseDTO invoice = createSampleInvoice();

        // When/Then: Attempt to generate PDF
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> pdfService.generateInvoicePdf(invoice, null)
        );

        assertEquals("OutputStream cannot be null", exception.getMessage());
    }

    @Test
    @DisplayName("PDF generation should complete in reasonable time for typical invoice")
    void generateInvoicePdf_PerformanceTest_CompletesInReasonableTime() {
        // Given: Invoice with 10 line items (typical size)
        InvoiceResponseDTO invoice = createInvoiceWithLineItems(10);
        when(templateEngine.process(anyString(), any(Context.class)))
            .thenReturn(createSimpleHtml(invoice));

        // When: Measure generation time
        long startTime = System.currentTimeMillis();
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);
        long duration = System.currentTimeMillis() - startTime;

        // Then: Generation completes within performance target
        assertNotNull(pdfBytes);
        assertTrue(duration < 3000,
            "PDF generation should complete in <3 seconds, but took " + duration + "ms");
    }

    @Test
    @DisplayName("PDF should contain invoice number in generated content")
    void generateInvoicePdf_ShouldIncludeInvoiceNumber() {
        // Given: Invoice with specific number
        InvoiceResponseDTO invoice = createSampleInvoice();
        String html = createSimpleHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated (content verification requires PDF parsing in integration test)
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
    }

    // Helper methods

    /**
     * Creates a sample invoice for testing
     */
    private InvoiceResponseDTO createSampleInvoice() {
        return new InvoiceResponseDTO(
            UUID.randomUUID(),
            "INV-2025-0001",
            UUID.randomUUID(),
            "Test Customer",
            "customer@example.com",
            LocalDate.now(),
            LocalDate.now().plusDays(30),
            InvoiceStatus.Draft,
            "Net 30",
            new BigDecimal("100.00"),
            new BigDecimal("10.00"),
            new BigDecimal("8.00"),
            new BigDecimal("98.00"),
            new BigDecimal("98.00"),
            List.of(createLineItem("Test Item", 1, "100.00")),
            "Test notes",
            1L,
            Instant.now(),
            Instant.now(),
            null
        );
    }

    /**
     * Creates an invoice with specified number of line items
     */
    private InvoiceResponseDTO createInvoiceWithLineItems(int count) {
        List<LineItemResponseDTO> lineItems = new java.util.ArrayList<>();
        for (int i = 0; i < count; i++) {
            lineItems.add(createLineItem("Item " + (i + 1), 1, "100.00"));
        }

        return new InvoiceResponseDTO(
            UUID.randomUUID(),
            "INV-2025-0001",
            UUID.randomUUID(),
            "Test Customer",
            "customer@example.com",
            LocalDate.now(),
            LocalDate.now().plusDays(30),
            InvoiceStatus.Draft,
            "Net 30",
            new BigDecimal(100 * count),
            BigDecimal.ZERO,
            BigDecimal.ZERO,
            new BigDecimal(100 * count),
            new BigDecimal(100 * count),
            lineItems,
            null,
            1L,
            Instant.now(),
            Instant.now(),
            null
        );
    }

    /**
     * Creates a line item for testing
     */
    private LineItemResponseDTO createLineItem(String description, int quantity, String price) {
        BigDecimal unitPrice = new BigDecimal(price);
        BigDecimal total = unitPrice.multiply(BigDecimal.valueOf(quantity));

        return new LineItemResponseDTO(
            UUID.randomUUID().toString(),
            description,
            quantity,
            unitPrice,
            BigDecimal.ZERO,
            BigDecimal.ZERO,
            total,
            BigDecimal.ZERO,
            total,
            BigDecimal.ZERO,
            total
        );
    }

    /**
     * Creates simple HTML for testing PDF generation
     */
    private String createSimpleHtml(InvoiceResponseDTO invoice) {
        return String.format("""
            <!DOCTYPE html>
            <html>
            <head>
                <title>Invoice %s</title>
            </head>
            <body>
                <h1>Invoice %s</h1>
                <p>Customer: %s</p>
                <p>Total: $%s</p>
            </body>
            </html>
            """,
            invoice.invoiceNumber(),
            invoice.invoiceNumber(),
            invoice.customerName(),
            invoice.totalAmount()
        );
    }

    /**
     * Validates that bytes represent a valid PDF by checking the PDF header
     */
    private boolean isPdfValid(byte[] pdfBytes) {
        if (pdfBytes == null || pdfBytes.length < 4) {
            return false;
        }

        // Check for PDF magic number: %PDF
        return pdfBytes[0] == 0x25 && // %
               pdfBytes[1] == 0x50 && // P
               pdfBytes[2] == 0x44 && // D
               pdfBytes[3] == 0x46;   // F
    }

    // Story 5.2: Template Enhancement Tests

    @Test
    @DisplayName("PDF template should include logo placeholder for company branding")
    void generateInvoicePdf_TemplateShouldIncludeLogoPlaceholder() {
        // Given: Invoice
        InvoiceResponseDTO invoice = createSampleInvoice();
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated successfully
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
        // Visual verification of logo placeholder (150x50px box) requires manual PDF inspection
    }

    @Test
    @DisplayName("PDF template should include company contact information area")
    void generateInvoicePdf_TemplateShouldIncludeCompanyContactInfo() {
        // Given: Invoice
        InvoiceResponseDTO invoice = createSampleInvoice();
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated with contact info placeholder
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
    }

    @Test
    @DisplayName("PDF should format currency values with dollar signs and decimals")
    void generateInvoicePdf_ShouldFormatCurrencyCorrectly() {
        // Given: Invoice with specific total amount
        InvoiceResponseDTO invoice = createSampleInvoice();
        String html = createEnhancedHtmlWithFormattedCurrency(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated with properly formatted currency
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
        // Currency format validation ($X,XXX.XX) happens in integration tests with text extraction
    }

    @Test
    @DisplayName("PDF should support multi-page invoices with 50+ line items")
    void generateInvoicePdf_WithManyLineItems_SupportsMultiplePages() {
        // Given: Invoice with 50 line items (multi-page scenario)
        InvoiceResponseDTO invoice = createInvoiceWithLineItems(50);
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated successfully for large invoice
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
        assertTrue(pdfBytes.length > 10000, "Multi-page PDF should be larger");
    }

    @Test
    @DisplayName("PDF should include status badge for Draft invoices")
    void generateInvoicePdf_DraftInvoice_IncludesStatusBadge() {
        // Given: Draft status invoice
        InvoiceResponseDTO invoice = createSampleInvoice();
        assertEquals(InvoiceStatus.Draft, invoice.status());
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated with status badge
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
    }

    @Test
    @DisplayName("PDF should include all table headers for line items")
    void generateInvoicePdf_LineItemsTable_IncludesAllHeaders() {
        // Given: Invoice with line items
        InvoiceResponseDTO invoice = createInvoiceWithLineItems(3);
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated with complete table structure
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
        // Table headers: Description, Quantity, Unit Price, Discount, Tax Rate, Amount
        // Verification happens in integration tests with text extraction
    }

    @Test
    @DisplayName("PDF should include totals section with subtotal, discount, tax, and total")
    void generateInvoicePdf_TotalsSection_IncludesAllCalculations() {
        // Given: Invoice with discount and tax
        InvoiceResponseDTO invoice = createSampleInvoice();
        String html = createEnhancedHtml(invoice);
        when(templateEngine.process(anyString(), any(Context.class))).thenReturn(html);

        // When: Generate PDF
        byte[] pdfBytes = pdfService.generateInvoicePdf(invoice);

        // Then: PDF is generated with complete totals section
        assertNotNull(pdfBytes);
        assertTrue(isPdfValid(pdfBytes));
        // Totals section includes: Subtotal, Total Discount, Total Tax, Total Amount, Balance Due
    }

    /**
     * Creates enhanced HTML with template improvements from Story 5.2
     */
    private String createEnhancedHtml(InvoiceResponseDTO invoice) {
        return String.format("""
            <!DOCTYPE html>
            <html>
            <head>
                <title>Invoice %s</title>
                <style>
                    .logo-placeholder { width: 150px; height: 50px; border: 2px dashed #ccc; }
                    .company-contact { font-size: 9pt; color: #666; }
                    .status-badge { padding: 4px 12px; background: #fef3c7; }
                </style>
            </head>
            <body>
                <div class="logo-placeholder">LOGO</div>
                <h1>%s</h1>
                <div class="status-badge">%s</div>
                <p>Invoice: %s</p>
                <p>Customer: %s</p>
                <p>Email: %s</p>
                <table>
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Qty</th>
                            <th>Unit Price</th>
                            <th>Discount</th>
                            <th>Tax Rate</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>Test Item</td><td>1</td><td>$100.00</td><td>10%%</td><td>8%%</td><td>$98.00</td></tr>
                    </tbody>
                </table>
                <div class="totals">
                    <div>Subtotal: $%s</div>
                    <div>Total Discount: -$%s</div>
                    <div>Total Tax: $%s</div>
                    <div><strong>Total Amount: $%s</strong></div>
                </div>
                <div class="company-contact">Company contact placeholder</div>
            </body>
            </html>
            """,
            invoice.invoiceNumber(),
            "InvoiceMe",
            invoice.status(),
            invoice.invoiceNumber(),
            invoice.customerName(),
            invoice.customerEmail(),
            invoice.subtotal(),
            invoice.totalDiscount(),
            invoice.totalTax(),
            invoice.totalAmount()
        );
    }

    /**
     * Creates HTML with formatted currency for testing
     */
    private String createEnhancedHtmlWithFormattedCurrency(InvoiceResponseDTO invoice) {
        return String.format("""
            <!DOCTYPE html>
            <html>
            <head><title>Invoice %s</title></head>
            <body>
                <h1>Invoice %s</h1>
                <p>Total: $1,234.56</p>
                <p>Customer: %s</p>
            </body>
            </html>
            """,
            invoice.invoiceNumber(),
            invoice.invoiceNumber(),
            invoice.customerName()
        );
    }
}
